##
## application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
#

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:

      change-log: classpath:db/migration/changes/changelog-master.yaml

jwt:
  secret: eR5$kL8@qT2#vM9*pX6&wC3%zN1!bV7^dF4
  expiration: 3600000

card:
  encryption:
    secret-key: aVeryStrongSecretKeyForAES256Bits_OrMore

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: Local Dev
        url: /v3/api-docs
    server: http://localhost:8081
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

logging:
  level:
    org.springframework.web: DEBUG
